/**
 * @file syntaxThemes.ts
 * @purpose Theme-specific syntax highlighting colors
 */

import type { SyntaxTheme } from "../styles";

export const SYNTAX_THEMES: Record<string, SyntaxTheme> = {
    light: {
        keyword: "#a626a4",
        string: "#50a14f",
        number: "#986801",
        comment: "#a0a1a7",
        function: "#4078f2",
        variable: "#e45649",
        operator: "#0184bc",
        punctuation: "#383a42",
        className: "#c18401",
        property: "#e45649",
        type: "#c18401",
        constant: "#986801",
        boolean: "#986801",
        regex: "#50a14f",
        tag: "#e45649",
        attribute: "#986801",
        default: "#383a42",
    },
    dark: {
        keyword: "#c678dd",
        string: "#98c379",
        number: "#d19a66",
        comment: "#5c6370",
        function: "#61afef",
        variable: "#e06c75",
        operator: "#56b6c2",
        punctuation: "#abb2bf",
        className: "#e5c07b",
        property: "#e06c75",
        type: "#e5c07b",
        constant: "#d19a66",
        boolean: "#d19a66",
        regex: "#98c379",
        tag: "#e06c75",
        attribute: "#d19a66",
        default: "#abb2bf",
    },
    nord: {
        keyword: "#81a1c1",
        string: "#a3be8c",
        number: "#b48ead",
        comment: "#616e88",
        function: "#88c0d0",
        variable: "#8fbcbb",
        operator: "#81a1c1",
        punctuation: "#d8dee9",
        className: "#8fbcbb",
        property: "#88c0d0",
        type: "#b48ead",
        constant: "#ebcb8b",
        boolean: "#ebcb8b",
        regex: "#a3be8c",
        tag: "#81a1c1",
        attribute: "#88c0d0",
        default: "#d8dee9",
    },
    catppuccin: {
        keyword: "#cba6f7",
        string: "#a6e3a1",
        number: "#fab387",
        comment: "#6c7086",
        function: "#89b4fa",
        variable: "#f5c2e7",
        operator: "#89dceb",
        punctuation: "#bac2de",
        className: "#f9e2af",
        property: "#89b4fa",
        type: "#f9e2af",
        constant: "#fab387",
        boolean: "#fab387",
        regex: "#a6e3a1",
        tag: "#cba6f7",
        attribute: "#89dceb",
        default: "#cdd6f4",
    },
    "tokyo-night": {
        keyword: "#bb9af7",
        string: "#9ece6a",
        number: "#7dcfff",
        comment: "#565f89",
        function: "#7aa2f7",
        variable: "#e0af68",
        operator: "#bb9af7",
        punctuation: "#c0caf5",
        className: "#e0af68",
        property: "#7aa2f7",
        type: "#e0af68",
        constant: "#ff9e64",
        boolean: "#ff9e64",
        regex: "#9ece6a",
        tag: "#bb9af7",
        attribute: "#7dcfff",
        default: "#a9b1d6",
    },
};

export function getSyntaxTheme(themeType: string): SyntaxTheme {
    return SYNTAX_THEMES[themeType] || SYNTAX_THEMES.light;
}
